### ISSUE TITLE
Any Document on building?

### ISSUE THREAD

**Issue by dsh0416** [faust93/android_device_meizu_m86#2]
I am using this ROM hard, and I've found a few bugs. I tried to change some code, but still unable to build the ROM like what I used to do on building official CM ports. So, if there to be any instructions on how to build it, so that I may provide some help on improving it.

**Comment by faust93** [comment]
What the problem exactly is? No special procedure to build, follow any CM building guide.

**Comment by dsh0416** [comment]
I would close this issue and open issues on specific problem I've met. Some of them has been fixed on 14.06.16 update.
