### ISSUE TITLE
Mobile data issues

### ISSUE THREAD

**Issue by dsh0416** [faust93/android_device_meizu_m86#3]
I've met problems with mobile data with 20160803 and 20160809 build.
The RIL seems to be fine because I can correctly receive SMS and calls.
But the mobile data doesn't work at all whatever RIL I use.
I've inserted 2 sim cards. One of them is TDD-LTE/GSM support, the other is FDD-LTE/WCDMA/GSM support. Neither of them could get mobile data connection.
I've tried to change preferred network type, but whatever option I choose, It doesn't work.
I've also tried to clear data/cache/dalvik, none of those helps.
The CM12.1 version works fine for me. So I'm wondering what if I could provide some debug info for further help?

**Comment by faust93** [comment]
Have you checked APN settings? is it ok?

**Comment by dsh0416** [comment]
APN settings checked. Nothing special.
Could it be a problem of the baseband version?

**Comment by dsh0416** [comment]
When I was using dual-sim card with the following configuration
![screenshot_20160815-194537](https://cloud.githubusercontent.com/assets/2303500/17663820/062f8c6c-6322-11e6-89d2-3f3f705c9df3.png)
It seems that the data service is still on Card 1(but disconnected)
Card 2 with only GSM network.
![screenshot_20160815-193514](https://cloud.githubusercontent.com/assets/2303500/17663841/346e49ce-6322-11e6-93a4-cf62b1851b3e.png)
![screenshot_20160815-193524](https://cloud.githubusercontent.com/assets/2303500/17663849/40206a0e-6322-11e6-8369-2d1aca177245.png)

Then I tried to remove the Card 1, and put my second card to card 1 slot.
It got LTE type correctly but still disconnected.
![screenshot_20160815-194133](https://cloud.githubusercontent.com/assets/2303500/17663888/9f18017a-6322-11e6-87c2-bcdc1e26f65d.png)

**Comment by faust93** [comment]
Check again APN settings. Try to remove default  APN and re add it by hands. Ensure that mobile data is enabled, try to check it on/off while doing "logcat -b radio >/sdcard/radio.log" in terminal. 
Try to place this file http://xep.8800.org/pro5/.tmp/modem.bin into /system/vendor/firmware and reboot (it's baseband used in cm12.1. if it will not help we can consider that the problem is on upper layer - ril libraries)

**Comment by dsh0416** [comment]
I've double checked the APNs, deleted and created twice.
Replaced modem, tested all 3 RIL libs.
Still not fixed, so that I uploaded my log of radio while switching mobile data.
[1.txt](https://github.com/faust93/android_device_meizu_m86/files/418103/1.txt)

**Comment by faust93** [comment]
Try to place http://xep.8800.org/pro5/.tmp/libril_smiril.so into /system/lib64 and reboot. Will it change something?

**Comment by dsh0416** [comment]
I've replaced the file. Baseband version becomes unknown. Then all signals turns to 0. Can't even register to network. I switched airplane mode, and made some logs.
[radio2.txt](https://github.com/faust93/android_device_meizu_m86/files/418292/radio2.txt)

**Comment by faust93** [comment]
Try this one http://xep.8800.org/pro5/.tmp/wholeril.zip
It is the whole RIL components (rild, libraries, baseband) used in CM12.1 build.
